// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9im6iGOEVpufUxN4fUjjLgOw4vd-UMNA',
    appId: '1:972893135954:web:b2e54d5a7ba563f1f1ab8b',
    messagingSenderId: '972893135954',
    projectId: 'uavapp-69420',
    authDomain: 'uavapp-69420.firebaseapp.com',
    storageBucket: 'uavapp-69420.appspot.com',
    measurementId: 'G-J72ZLR5MEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_UcD_ZVPtKzUl31aJt3STZfXOpQv9vGA',
    appId: '1:972893135954:android:a3cde4f4dd98df74f1ab8b',
    messagingSenderId: '972893135954',
    projectId: 'uavapp-69420',
    storageBucket: 'uavapp-69420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7hbS8RnuI1SXL5bV2WhGD1Ic6mhMl92I',
    appId: '1:972893135954:ios:3306f5614cd72f97f1ab8b',
    messagingSenderId: '972893135954',
    projectId: 'uavapp-69420',
    storageBucket: 'uavapp-69420.appspot.com',
    iosClientId: '972893135954-pgqna0gpoq2kpchvgt8rjn75enj8ch3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.uavapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7hbS8RnuI1SXL5bV2WhGD1Ic6mhMl92I',
    appId: '1:972893135954:ios:3306f5614cd72f97f1ab8b',
    messagingSenderId: '972893135954',
    projectId: 'uavapp-69420',
    storageBucket: 'uavapp-69420.appspot.com',
    iosClientId: '972893135954-pgqna0gpoq2kpchvgt8rjn75enj8ch3l.apps.googleusercontent.com',
    iosBundleId: 'com.example.uavapp',
  );
}
